/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_integer_ffmpeg_nativeintf_FFmpegNativeJ */

#ifndef _Included_com_integer_ffmpeg_nativeintf_FFmpegNativeJ
#define _Included_com_integer_ffmpeg_nativeintf_FFmpegNativeJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_integer_ffmpeg_nativeintf_FFmpegNativeJ
 * Method:    initial
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_integer_ffmpeg_nativeintf_FFmpegNativeJ_initial
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_integer_ffmpeg_nativeintf_FFmpegNativeJ
 * Method:    encode
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_integer_ffmpeg_nativeintf_FFmpegNativeJ_encode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_integer_ffmpeg_nativeintf_FFmpegNativeJ
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_integer_ffmpeg_nativeintf_FFmpegNativeJ_flush
  (JNIEnv *, jobject);

/*
 * Class:     com_integer_ffmpeg_nativeintf_FFmpegNativeJ
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_integer_ffmpeg_nativeintf_FFmpegNativeJ_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
